### ISSUE TITLE
how to import a coffeescript module?

### ISSUE THREAD

**Issue by BryanCrotaz** [embroider-build/ember-auto-import#132]
Trying to import a module written in coffee script:

https://github.com/meltingice/psd.js

**Comment by ef4** [comment]
If you want to customize your webpack config you can make it work. See https://github.com/meltingice/psd.js/issues/51

But I think this whole pattern is a fairly bad hack, and library authors should publish Javascript to NPM, even if they author in coffeescript, etc.

**Comment by BryanCrotaz** [comment]
Tried adding an alias:
```
options: {
  autoImport: {
    alias: {
      'browser-psd': 'browser-psd/dist/psd.js'
    }
  }
}
```
Still get the same error

**Comment by BryanCrotaz** [comment]
It appears to be publishing as a UMD module. Is this supported by `ember-auto-import`?

**Comment by BryanCrotaz** [comment]
Aha - I think this is the same problem with typescript as #131

**Comment by NullVoxPopuli** [comment]
Hello @BryanCrotaz does this issue still need resolving?

**Comment by BryanCrotaz** [comment]
Only if coffeescript is still a thing. I haven't seen any coffeescript in years.
