### ISSUE TITLE
don't produce empty sourcemap file

### ISSUE THREAD

**Issue by villander** [embroider-build/ember-auto-import#144]
@ef4 when I use a plugin to deploy sourcemaps like this: `ember-cli-deploy-rollbar` or `ember-cli-deploy-sentry`

ember-auto-import generate a file.map empty

```
auto-import-fastboot-81f919f3d82c38703c7b0de8c4c4a874.map
{"version":3,"sources":[],"names":[],"mappings":"","file":"auto-import-fastboot.js"}
```

all APIs like rollbar, sentry, and airbrake reject empty .map files. We need to disable this in ember-auto-import or generate a source map that contains something

![image](https://user-images.githubusercontent.com/10222774/47862724-8e990b80-ddd4-11e8-8762-278e220280ea.png)

**Comment by NullVoxPopuli** [comment]
in ember-auto-import@v2 we have original-source source-maps, (so you see TS in the browser if you author in TS, etc)
![image](https://github.com/embroider-build/ember-auto-import/assets/199018/44518725-67c5-4d27-9101-df9d3fa9776b)
