### ISSUE TITLE
Allow empty modules alias

### ISSUE THREAD

**Issue by kanongil** [embroider-build/ember-auto-import#146]
In my app, I produce multiple build variants and I would like to disable an import for some of these. Currently I do this by conditionally aliasing to an empty module, like https://github.com/PagerDuty/empty-module.

Ideally, I would not need this hack. Maybe a value of `false` could do something similar?

**Comment by NullVoxPopuli** [comment]
> That is also a thing I want to make soon,

[`@embroider/macros`](https://www.npmjs.com/package/@embroider/macros) You did it!!!
