### ISSUE TITLE
Application broke with transpilation of modules due to amd-define being imported

### ISSUE THREAD

**Issue by ncoden** [embroider-build/ember-auto-import#154]
Hello 👋 

Since `ember-auto-import@1.2` when used with `babel`, the built application with transpiled modules is looking for the `amd-define` module that webpack cannot provide.

 

<details><summary>1. With this configuration in <code>ember-cli-build.js</code>...</summary>
 

```js
// NPM packages importer for Ember
// See https://github.com/ef4/ember-auto-import
autoImport: {
  webpack: {

    // Some modules may import node builtin but without using them
    // in browser contexts. We tell webpack to ignore them.
    // See https://github.com/request/request/issues/1529
    node: {
      console: true,
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
    },

    // Transpile all modules with Babel.
    // Prevent the transformation of module so the Webpack bundler
    // can detect them and handle them better.
    // See https://babeljs.io/docs/en/babel-preset-env#modules
    module: {
      rules: [{
          test: /\.js$/,
          use: [{
              loader: 'babel-loader',
              options: { presets: [['babel-preset-env', { modules: false }]] },
          }],
      }],
    },

  },
},

'ember-cli-babel': {
  includePolyfill: true,
},
```

</details>
 
<details><summary>2. I get this warning during the build</summary>

```log
WARNING in ./tmp/bundler-cache_path-9lf4KnLJ.tmp/staging/l.js 2:16-23
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

</details>
 
<details><summary>3. The following error is thrown in the browser</summary>

```log
amd-define.js:2 Uncaught Error: define cannot be used indirect
    at module.exports (webpack://__ember_auto_import__/(:4200/webpack)/buildin/amd-define.js?:2:8)
    at eval (app.js:15)
    at eval (app.js:51)
    at Object../tmp/bundler-cache_path-9lf4KnLJ.tmp/staging/app.js (vendor-suffix.js:1)
    at __webpack_require__ (vendor-suffix.js:1)
    at eval (app.js:2)
    at Object.0 (vendor-suffix.js:1)
    at __webpack_require__ (vendor-suffix.js:1)
    at checkDeferredModules (vendor-suffix.js:1)
    at Array.webpackJsonpCallback [as push] (vendor-suffix.js:1)
```

</details>
 
<details><summary>4. Coming from a static error in place of the <code>amd-define</code> module</summary>

```js
/*!***************************************!*\
  !*** (webpack)/buildin/amd-define.js ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports) {

eval("module.exports = function() {\r\n\tthrow new Error(\"define cannot be used indirect\");\r\n};\r\n\n\n//# sourceURL=webpack://__ember_auto_import__/(webpack)/buildin/amd-define.js?");

/***/ }),
```

</details>

 

I seen that there is some special treatment in the build process of this package for the "loader" `l.js` and the AMD and CJS helpers `define` and `require` so they are not included in the build.

I guess that when the imported modules are transpiled using babel, this special treatment is not working and webpack try to include the `define` helper in the build.

My solution for now is to stay at `ember-auto-import@1.1.0`, without the "dynamic import" feature.

**Comment by ncoden** [comment]
Poke @ef4 👋

**Comment by ncoden** [comment]
By the way, thank you for the babel7 support.

**Comment by ef4** [comment]
Well, you make a good point, which is that if your goal is a safe minimum feature level, you don't want to ignore _any_ files if you can help it.

Now that I look closely, it really doesn't seem like babel's fault here, I doubt babel is doing anything to `l.js` that breaks the build. Rather it seems that applying babel-loader to it causes webpack to ignore our `noParse` directive.

Which is surprising in the sense that those things shouldn't interfere, but also not surprising because webpack configs API is so byzantine.

Perhaps you can experiment and see if there is a combination of incantations that would let noParse and your rule coexist? Like, perhaps the noParse condition needs to be worded differently so that it still matches post-babel-loader.

**Comment by mansona** [comment]
I'm closing this issue because it's old and it seems like there was no more conversation about recreating this issue. If you still want to work on this let me know and I'll re-open the issue 👍
