### ISSUE TITLE
How to dynamically import local modules?

### ISSUE THREAD

**Issue by smfoote** [embroider-build/ember-auto-import#158]
I would like to be able to dynamically import a file into my Ember addon based on a condition, but I have not had success in doing so. I have been successful with dynamic imports of npm packages, though, and in those cases I can see the chunk created in the /dist folder. With dynamic imports of local files, however, no chunk is created in the /dist folder and I get the following runtime error in the console in Chrome:

```
Could not find module `_eai_dyn_../utils/t-chameleon` imported from `(require)`
```

The code I am using to handle the import:

```js
if (NEEDS_MODULE) {
  import('../utils/heavy-module')
    .then(module => module.default)
    .then(module => module.init());
}
```

Is it possible to dynamically import a local file? If so, how can it be done? What am I doing wrong?

**Comment by ef4** [comment]
ember-auto-import only handles imports from other packages. Relative paths to your own package are ignored. (This goes for both static and dynamic imports.)

The rationale is that it's not really practical to start pulling in parts of an application without having a more holistic view of what is already included in any given bundle. I am working hard on solving that problem, but it involves [making the whole ember-cli build pipeline work more like ember-auto-import](https://github.com/embroider-build/embroider).

I would suggest creating an actual NPM package to hold your heavy things and auto-importing that. You don't actually need to publish it, it can be a subdirectory of your app's repo, with an entry in package.json and a symlink in node_modules to make it resolvable. The main point is make it clear that it's separate, and make it clear that it would be a mistake for it to try to import other files from the app.

**Comment by anlumo** [comment]
I had the same issue with a package imported via `npm link`, this causes the same error (package can't be found). I assume that ember-auto-import scans the package.json file, and thus your workaround with the symlink doesn't work.

The exact same package does work when I use `npm install` with a local path, though. However, then I have to update the module every time I change something.

**Comment by mansona** [comment]
This will be implemented by the stuff I'm working on https://github.com/embroider-build/ember-auto-import/pull/587 🎉
