### ISSUE TITLE
Cannot read property toString of undefined for PollyJS persister-fs

### ISSUE THREAD

**Issue by allthesignals** [embroider-build/ember-auto-import#164]
Hi there, 

I'm working with (PollyJS)[https://netflix.github.io/pollyjs/#/test-frameworks/qunit]'s QUnit helper and its file system persister feature. This allows caching of certain network responses. 

I'm seeing some webpack/
ember_auto_import" errors:

> Uncaught TypeError: Cannot read property 'toString' of undefined
>     at Object.eval (graceful-fs.js:63)
>     at eval (graceful-fs.js:281)
>     at Object../node_modules/graceful-fs/graceful-fs.js (test-support-suffix.js:7)
>     at __webpack_require__ (test-support-suffix.js:7)
>     at eval (index.js:4)
>     at Object../node_modules/@pollyjs/node-server/node_modules/fs-extra/lib/fs/index.js (test-support-suffix.js:7)
>     at __webpack_require__ (test-support-suffix.js:7)
>     at eval (index.js:8)
>     at Object../node_modules/@pollyjs/node-server/node_modules/fs-extra/lib/index.js (test-support-suffix.js:7)
>     at __webpack_require__ (test-support-suffix.js:7)

This dependency relies on `fs` and `net`. I'm not totally familiar with `net`, however, I went ahead and added the following to my ember-cli-build configuration:

```javascript
// ember-cli-build.js

    autoImport: {
      webpack: {
        node: {
          fs: 'empty',
          net: 'empty',
        },
        module: {
          rules: [
            /* see: https://github.com/graphql/graphql-js/issues/1272#issuecomment-393903706 */
            {
              test: /\.mjs$/,
              include: /node_modules\/@turf\/difference/,
              type: 'javascript/auto',
            },
          ],
        },
      },
    }
```

What does it mean to set `fs` or `net` to 'empty'? I found that particular workaround at https://github.com/ef4/ember-auto-import/issues/126. I'm confident setting `fs` to 'empty' is probably fine - but without setting net to empty, I see this error:

> ERROR in ./node_modules/express/lib/request.js
> Module not found: Error: Can't resolve 'net' in '/Users/mgardner/labs-applicant-maps/node_modules/express/lib'

With the configuration you see above, my test suite fails with the global error also quoted. The relevant code for `toString`, though, is found in `graceful-fs`:

```javascript

// Only patch fs once, otherwise we'll run into a memory leak if
// graceful-fs is loaded multiple times, such as in test environments that
// reset the loaded modules between tests.
// We look for the string `graceful-fs` from the comment above. This
// way we are not adding any extra properties and it will detect if older
// versions of graceful-fs are installed.
if (!/\bgraceful-fs\b/.test(fs.closeSync.toString())) {
  fs.closeSync = module.exports.closeSync;
  fs.close = module.exports.close;
}
```

Any thoughts? It looks like this is undefined:

`fs.closeSync`

**Comment by mansona** [comment]
> Feel free to close and bring this discussion to Polly's repo.

I'm closing this on our side 👍 

Let me know if you want me to open it up again and we'll happily take a look
