### ISSUE TITLE
Cannot browserify Node std lib

### ISSUE THREAD

**Issue by ericyoungberg** [embroider-build/ember-auto-import#168]
In your previous solution, I was able to do `import uuid from 'npm:uuid';` but I am no longer able to do so; I receive the error message: 

```
Error: Could not find module `uuid` imported from `app/path/etc`
```

The same result occurs regardless if I address the package as `npm:uuid` or just `uuid`

**Comment by alexlafroscia** [comment]
Is this the package you're trying to install?

https://github.com/kelektiv/node-uuid

Do you have it in your `dependencies`?

**Comment by mansona** [comment]
I'm assuming that the lack of response means that this isn't an issue any more 😂 Let me know if you have a reproduction of the problem and I can re-open this issue 👍
