### ISSUE TITLE
"browser" entrypoint doesn't work for json-schema-faker

### ISSUE THREAD

**Issue by H1D** [embroider-build/ember-auto-import#172]
Trying to use e-auto-import with [json-schema-faker](https://github.com/json-schema-faker/json-schema-faker) and it fails to build.

Here is terminal output:
```bash
ERROR in ./node_modules/jsonpath/generated/parser.js
Module not found: Error: Can't resolve 'fs' in '/Users/artem_sushchev/proj/sandbox/ember-auto-import-json-schema-faker-issue/node_modules/jsonpath/generated'
 @ ./node_modules/jsonpath/generated/parser.js 715:17-30
 @ ./node_modules/jsonpath/lib/parser.js
 @ ./node_modules/jsonpath/lib/index.js
 @ ./node_modules/jsonpath/index.js
 @ ./node_modules/json-schema-faker/dist/json-schema-faker.min.js
 @ /private/var/folders/mn/rrvfthbn6mnf92s1m3f3b__4kq33dv/T/broccoli-96499Tdv5xXwJcgEJ/cache-176-bundler/staging/app.js
 @ multi /private/var/folders/mn/rrvfthbn6mnf92s1m3f3b__4kq33dv/T/broccoli-96499Tdv5xXwJcgEJ/cache-176-bundler/staging/l.js /private/var/folders/mn/rrvfthbn6mnf92s1m3f3b__4kq33dv/T/broccoli-96499Tdv5xXwJcgEJ/cache-176-bundler/staging/app.js

ERROR in ./node_modules/jsonpath/lib/grammar.js
Module not found: Error: Can't resolve 'fs' in '/Users/artem_sushchev/proj/sandbox/ember-auto-import-json-schema-faker-issue/node_modules/jsonpath/lib'
 @ ./node_modules/jsonpath/lib/grammar.js 2:9-22
 @ ./node_modules/jsonpath/lib/parser.js
 @ ./node_modules/jsonpath/lib/index.js
 @ ./node_modules/jsonpath/index.js
 @ ./node_modules/json-schema-faker/dist/json-schema-faker.min.js
 @ /private/var/folders/mn/rrvfthbn6mnf92s1m3f3b__4kq33dv/T/broccoli-96499Tdv5xXwJcgEJ/cache-176-bundler/staging/app.js
 @ multi /private/var/folders/mn/rrvfthbn6mnf92s1m3f3b__4kq33dv/T/broccoli-96499Tdv5xXwJcgEJ/cache-176-bundler/staging/l.js /private/var/folders/mn/rrvfthbn6mnf92s1m3f3b__4kq33dv/T/broccoli-96499Tdv5xXwJcgEJ/cache-176-bundler/staging/app.jsBuild Error (Bundler)
```

 – looks like there is some browser unfriendly code!

Thing is that it has browser entrypoint – https://github.com/json-schema-faker/json-schema-faker/blob/master/package.json#L8

Not sure is it really browser-friendly since it require `jsonpath` in some cases which isn't browser friendly – https://github.com/json-schema-faker/json-schema-faker/blob/master/dist/json-schema-faker.js#L7

Here is repo reproding issue – https://github.com/H1D/ember-auto-import-json-schema-faker-issue

**Comment by samselikoff** [comment]
I'm also trying to get ember-auto-import to use the `browser` key for `@miragejs/server`, but it doesn't seem to be working. I think `main` might take precedence.

**Comment by ef4** [comment]
See 

https://github.com/ef4/ember-auto-import/blob/e7d34659666ece3a33c822971e12720680b86c89/packages/ember-auto-import/ts/splitter.ts#L21

and

https://github.com/ef4/ember-auto-import/blob/e7d34659666ece3a33c822971e12720680b86c89/packages/ember-auto-import/ts/splitter.ts#L230

to debug whether we're really not prioritizing the browser field.

**Comment by samselikoff** [comment]
Nevermind! We had a typo in our build over in @miragejs/server.

**Comment by mansona** [comment]
seems like this is ok for now 👍  I'm closing this and let me know if you need me to re-open it
