### ISSUE TITLE
Sharing local node code with the client?

### ISSUE THREAD

**Issue by samselikoff** [embroider-build/ember-auto-import#188]
I did some digging and found [this comment](https://github.com/ef4/ember-auto-import/issues/158#issuecomment-443063971), but figured I'd ask: is it possible to use Auto Import to make a local node module (e.g.`/ember-cli-addon-docs/lib/utils/render-markdown`) available to my ember app to import? (e.g. from `/ember-cli-addon-docs/addon/utils/render-markdown` or `/ember-cli-addon-docs/tests/dummy/routes/application.js`)

**Comment by buschtoens** [comment]
As of _now_, the only real solution is still what has been described in #158.

If you are using yarn, you can make this work more easily via a workspace. If you want to use npm, you can use lerna to emulate a yarn workspace.

**Comment by samselikoff** [comment]
hm. Gotcha.

I remembered that in Ember CLI Tailwind we actually accomplish this by authoring the shared code in ES6 modules, and [running it through Rollup when we need to use it in Node](https://github.com/embermap/ember-cli-tailwind/blob/master/lib/build-tailwind.js#L25). I think I'm going to try this because I really just need a simple function/class, and setting up a workspace just for that seems like overkill.

**Comment by samselikoff** [comment]
@buschtoens I saw in that thread that Ed said you didn't need a workspace, just a symlinked local subdir. Do you have any knowledge of how that works? How & when to do the symlinking in a way that works for npm/yarn projects?

I wonder if it's possible to point to the subdir using relative paths in the `package.json` entry?

**Comment by buschtoens** [comment]
While I would still recommend workspaces, you can use [`file:`](https://docs.npmjs.com/files/package.json#local-paths) to specify a local path as a dependency. You'll probably have to add a `package.json` to the target directory, but I am not 💯 sure about that.

**Comment by samselikoff** [comment]
cool, thanks for the reply.

Do you know of an example oss project/ember addon that uses workspaces?

**Comment by samselikoff** [comment]
FWIW things seem to work when I

1. Create these files

```js
// addon-docs-shared/foo.js
module.exports = function foo() {
  console.log('the foo function from addon-docs-shared!');
};
```

```js
// addon-docs-shared/package.json`
{
  "name": "addon-docs-shared",
  "version": "1.0.0"
}
```

2. Update my project's `package.json`:

```diff
  "dependencies": {
+   "addon-docs-shared": "./addon-docs-shared",
  }
```

3. Add some linking code that runs in the `prepare` script:

```js
// package.json

"scripts": {
  "prepare": "./scripts/link-them.sh"
},
```

```sh
# scripts/link-them.sh

#!/bin/bash

# addon-docs-shared gets linked, so its packages can be used in node & ember
mkdir -p ./node_modules
pushd ./node_modules > /dev/null
rm -rf ./addon-docs-shared
ln -s ../addon-docs-shared ./addon-docs-shared
popd > /dev/null
```

Now I can do this

```js
// index.js
const foo = require('addon-docs-shared/foo');

foo();
```

and also this

```js
// tests/dummy/app/routes/application.js

import Route from '@ember/routing/route';
import foo from 'addon-docs-shared/foo';

export default Route.extend({

  model() {
    foo();
  }

});
```

Pretty cool!

**Comment by ef4** [comment]
If your use case is just writing a module that can be loaded in both ember and node, another pretty easy option is to author it as an ES module and use `@std/esm` to import it in node.

For example, [this module](https://github.com/cardstack/cardstack/blob/master/packages/test-support/addon/jsonapi-factory.js) is consumed normally as part of an addon, but it can also be required in node [because of this](https://github.com/cardstack/cardstack/blob/master/packages/test-support/jsonapi-factory.js).

**Comment by samselikoff** [comment]
Nice. I think I did this at one point in Tailwind. And yeah I think that would be ideal, bc we get to avoid the linking stuff...

**Comment by samselikoff** [comment]
And the ES module would have access to node packages, thanks to Auto Import, correct?

**Comment by ef4** [comment]
Yes, you could also still do that.

**Comment by samselikoff** [comment]
👏 works way better! Author in ES6, no global fake npm packages, no symlinking, no updates to gitignore or npmignore. Sweet!

**Comment by samselikoff** [comment]
Here's the change: https://github.com/ember-learn/ember-cli-addon-docs/pull/321/files

Powerful tools man. Can't wait till they become more accessible, there's so much power here and I think most folks don't know how to use it.

**Comment by samselikoff** [comment]
Running into an issue in testing:

> not ok 1 Chrome 72.0 - [undefined ms] - Global error: Uncaught Error: QUnit has already been defined. at webpack://__ember_auto_import__/./node_modules/qunit/qunit/qunit.js?, line 2896

[Here's the line in travis.](https://travis-ci.org/ember-learn/ember-cli-addon-docs/jobs/492303261#L509)

It's weird because everything is working in development.

There is [one test](https://github.com/ember-learn/ember-cli-addon-docs/blob/master/tests-node/unit/utils/compile-markdown-test.js) that uses the shared module, but even if I delete that I still get the error.

Any ideas?

**Comment by AddisonG** [comment]
@samselikoff - I'm also getting that error:

```
not ok 1 Chrome 77.0 - [undefined ms] - Global error: Uncaught Error: QUnit has already been defined. at webpack://__ember_auto_import__/./node_modules/qunit/qunit/qunit.js?, line 3944
    ---
        browser log: |
            testContext: [object Object]
            ERROR: Uncaught Error: QUnit has already been defined. at webpack://__ember_auto_import__/./node_modules/qunit/qunit/qunit.js?, line 3944
```

Any ideas? Solutions?

**Comment by ef4** [comment]
I think that's a pretty general error caused any time you end up with more than one copy of QUnit. Can't tell exactly why without more detail, and it's probably a separate issue from this one.

**Comment by NullVoxPopuli** [comment]
Based on the discussion, it looks like this is resolved. If I'm mistaken (which is quite often!), please feel free to open a new issue, and we can have a fresh discussion over there ✨✨✨ 

Thank you!!
