### ISSUE TITLE
Cannot import file from vendor

### ISSUE THREAD

**Issue by devotox** [embroider-build/ember-auto-import#197]
`import formMain from '../../vendor/forms/design/form-options/navigation';`

File not found running above or removing all the `../`

**Comment by buschtoens** [comment]
ember-auto-import can only import actual packages. You might be interested in this discussion: https://github.com/ef4/ember-auto-import/issues/188

**Comment by devotox** [comment]
Thank you @buschtoens

**Comment by NullVoxPopuli** [comment]
I think this has been resolved, so I'm going to close -- if I'm mistaken, please open a new discussion, and I'll be happy to help! :sparkles:
