### ISSUE TITLE
Not working on ember-cli 2.5

### ISSUE THREAD

**Issue by FutoRicky** [embroider-build/ember-auto-import#43]
The addon is currently not working on ember 2.5.0. Is it intended to only work v3.xx and up? Thanks.

**Comment by ef4** [comment]
Do you mean ember-cli 2.5?

(A lot of people try to stick to matching versions of ember and ember-cli and so think of them as the same thing, but really they can be widely mixed and matched.)

At the moment I'm testing back as far as ember-cli 2.12. We can probably go significantly further with a few tweaks.

**Comment by NullVoxPopuli** [comment]
👋 ember-auto-import now only supports ember-source and ember-cli 3.4 and higher.

Earlier version of ember-auto-import can be used on lower versions of ember-cli, tho!
