### ISSUE TITLE
Release 2.6.2+ broken due to missing @babel/traverse

### ISSUE THREAD

**Issue by runspired** [embroider-build/ember-auto-import#580]
This may be a peer-dep installation issue or a peer-dep needing to be declared, as in CI (but not locally) we see this: `babel-plugin-ember-template-compilation/src/node-main.js)Error: [BABEL]: Cannot find module '@babel/traverse'`

> tests/request test: - /home/runner/work/data/data/node_modules/.pnpm/broccoli-babel-transpiler@7.8.1/node_modules/broccoli-babel-transpiler/lib/worker.js (While processing: /home/runner/work/data/data/node_modules/.pnpm/babel-plugin-ember-template-compilation@2.0.2/node_modules/babel-plugin-ember-template-compilation/src/node-main.js)Error: [BABEL]: Cannot find module '@babel/traverse'

After isolating various in-flight dependency bumps, we see the only bump that causes this is that of ember-auto-import from 2.6.1

The [lockfile diff](https://github.com/emberjs/data/pull/8679/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb) contains very few changes other than the ember-auto-import version change: 

This one stands out as an addition of a previously non-existent dependency

```
 /babel-plugin-ember-template-compilation@2.0.3:
    resolution: {integrity: sha512-SIetZD/uCLnzIBTJtzYGc2Q55TPqM5WyjuOgW+Is1W3SZVljlY3JD5Add29hDMs//OvXBWoXfOopQxkfG4/pIA==}
    engines: {node: '>= 12.*'}
    dependencies:
      babel-import-util: 1.3.0
```

**Comment by NullVoxPopuli** [comment]
Hello! thanks for reporting! 
Can you provide a repro repo?

**Comment by runspired** [comment]
EmberData. Every drifting dep test run fails this way, or bump anything related to embroider locally and observe failure (addon-dev for instance)

**Comment by runspired** [comment]
Fix is in https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/24
