### ISSUE TITLE
error after ember upgrade - Module not found: Error: Can't resolve 'ember-qunit/qunit-module'

### ISSUE THREAD

**Issue by poplevente** [embroider-build/ember-auto-import#612]
hi all,

i'm recently updating from ember 3.12 to the latest and once running the ember addon (via ember serve), i get the following error

ERROR in ..\AppData\Local\Temp\broccoli-22636UwUwkHtLmdQ5\cache-221-webpack_bundler_ember_auto_import_webpack\tests.cjs 20:112-147
Module not found: Error: Can't resolve 'ember-qunit/qunit-module' in '..\AppData\Local\Temp\broccoli-22636UwUwkHtLmdQ5\cache-221-webpack_bundler_ember_auto_import_webpack'

can someone point me to a direction what could be?

**Comment by ef4** [comment]
Do you have code in your app that is trying to import `ember-qunit/qunit-module`? That was an internal implementation detail of old versions of ember-qunit. It was never public API as far as I know.

Whatever is trying to import that should just import from `qunit` instead.

**Comment by poplevente** [comment]
nice, thanks. that was it.
