### ISSUE TITLE
Tolerate @glimmer/component v2 addon without explicit dependency

### ISSUE THREAD

**Issue by ef4** [embroider-build/ember-auto-import#644]
@glimmer/component just released as a v2 addon. This is causing people to hit the assertion in ember-auto-import like:

```
@fortawesome/ember-fontawesome tried to import "@glimmer/component" in "@fortawesome/ember-fontawesome/components/fa-icon.js" from addon code, but "@glimmer/component" is a devDependency. You may need to move it into dependencies.
```

This is a bug, we don't want to force everybody to declare a peer or dep on @glimmer/component.

I think this may already be fixed (accidentally) by the changes in #642, so I'm releasing ember-auto-import 2.9 and will test to confirm.

**Comment by ef4** [comment]
I see at least two distinct problem reports. The assertion above is one, and we can fix that in ember-auto-import.

The other is what happens if an addon doesn't have a dependency on ember-auto-import at all. I'm less sure we should attempt to fix that. An addon without EAI support can't use any v2 addons, and really really just needs to add the dependency on EAI.

**Comment by ef4** [comment]
Can confirm this is fixed in ember-auto-import 2.9.0.

When updating an app to @glimmer/component 2.0 one should also update ember-auto-import in the app to 2.9.0, and then this assertion will not hit.

The actual fix in ember-auto-import was that it's smarter about resolving v2 addons from within other addons now. It knows that @glimmer/component is a v2 addon that may need to be accessible to code that didn't necessarily have it as a dependency.

**Comment by simonihmig** [comment]
> The other is what happens if an addon doesn't have a dependency on ember-auto-import at all. I'm less sure we should attempt to fix that. An addon without EAI support can't use any v2 addons, and really really just needs to add the dependency on EAI.

@ef4 just to confirm my understanding here: if you talk about "an addon", you are meaning "a v1 addon" really, while v2 addons don't need to care about eai at all, right?

**Comment by ef4** [comment]
Correct, I mean v1 addons. V2 addons necessarily get "imports from NPM" automatically and don't need an EAI dependency.
