### ISSUE TITLE
builds are broken when webpack mode == 'production' and minification is enabled

### ISSUE THREAD

**Issue by g-cassie** [embroider-build/ember-auto-import#83]
We are using `ember-auto-import` to import PusherJS.  When production builds are minified, PusherJS does not function correctly.  When production builds are not-minified, everything works.

After some sleuthing, we determined that `ember-auto-import` sets `mode == 'production` on the webpack config which causes webpack to minify PusherJS.

I think what is happening is ember then does a second pass of minification which causes the PusherJS code to break.  This is a complete guess though.

Any advice on how to debug this further? For now we have set webpack mode to 'development' for all builds and it seems to work.

**Comment by lukemelia** [comment]
Thanks @backspace. We had the same error and your fix worked.

**Comment by NullVoxPopuli** [comment]
can this be closed?

**Comment by NullVoxPopuli** [comment]
For libraries which break when minified / compiled multiple times, there is the option to skipBabel, provided by ember-auto-import:
```js
// In your ember-cli-build.js file
let app = new EmberApp(defaults, {
  autoImport: {
    skipBabel: [
      {
        package: 'pusherjs',
        semverRange: '*',
      },
    ],
  },
});
```
